### ISSUE TITLE
Regression in 1.4.5 on macOS: `Fl_cocoa.mm: error: ‘NSEventModifierFlagFunction’ was not declared in this scope`

### ISSUE THREAD

**Issue by barracuda156** [fltk/fltk#1424]
FLTK 1.4.5 fails to build on 10.6, while 1.4.4 built fine.
```
--->  Configuring fltk
Warning: ccache_dir /opt/local/var/macports/build/.ccache could not be initialized; disabling ccache: couldn't execute "ccache": no such file or directory
Executing:  cd "/opt/local/var/macports/build/fltk-08af0cac/work/fltk-1.4.5" && ./configure --prefix=/opt/local --enable-shared --disable-localjpeg --disable-localzlib --disable-localpng --with-archflags="-arch ppc" 
checking build system type... powerpc-apple-darwin10.8.0
checking host system type... powerpc-apple-darwin10.8.0
checking for gcc... /usr/bin/gcc-4.2
checking whether the C compiler works... yes
checking for C compiler default output file name... a.out
checking for suffix of executables... 
checking whether we are cross compiling... no
checking for suffix of object files... o
checking whether the compiler supports GNU C... yes
checking whether /usr/bin/gcc-4.2 accepts -g... yes
checking for /usr/bin/gcc-4.2 option to enable C11 features... unsupported
checking for /usr/bin/gcc-4.2 option to enable C99 features... -std=gnu99
checking whether the compiler supports GNU C++... yes
checking whether /usr/bin/g++-4.2 accepts -g... yes
checking for /usr/bin/g++-4.2 option to enable C++11 features... unsupported
checking for /usr/bin/g++-4.2 option to enable C++98 features... unsupported
checking for pkg-config... /opt/local/bin/pkg-config
checking for a BSD-compatible install... /usr/bin/install -c
checking for nroff... /usr/bin/nroff
checking for doxygen... no
checking for ranlib... ranlib
checking for ar... /opt/local/bin/ar
checking for windres... no
checking for stdio.h... yes
checking for stdlib.h... yes
checking for string.h... yes
checking for inttypes.h... yes
checking for stdint.h... yes
checking for strings.h... yes
checking for sys/stat.h... yes
checking for sys/types.h... yes
checking for unistd.h... yes
checking size of short... 2
checking size of int... 4
checking size of long... 4
checking for dirent.h that defines DIR... yes
checking for library containing opendir... none required
checking for sys/select.h... yes
checking for sys/stdtypes.h... no
checking whether we have the POSIX compatible scandir() prototype... no
checking for scandir... yes
checking for vsnprintf... yes
checking for snprintf... yes
checking for strings.h... (cached) yes
checking for strcasecmp... yes
checking for strlcat... yes
checking for strlcpy... yes
checking for locale.h... yes
checking for localeconv... yes
checking for setenv... yes
checking for library containing pow... none required
checking for math.h... yes
checking for trunc... yes
checking for special C compiler options needed for large files... no
checking for _FILE_OFFSET_BITS value needed for large files... no
checking for long long int... yes
checking for library containing dlsym... none required
checking for dlfcn.h... yes
checking for jpeg_CreateCompress in -ljpeg... yes
checking for jpeglib.h... yes
checking for gzgets in -lz... yes
checking for zlib.h... yes
checking for libpng-1.6.x... yes
checking for png_get_valid in -lpng... yes
checking for png_set_tRNS_to_alpha in -lpng... yes
checking for pthread.h... yes
checking for pthread_create using -lpthreads... no
checking for pthread_create using -lpthread... yes
checking for pthread_create using -pthread... yes
checking whether we have PTHREAD_MUTEX_RECURSIVE... yes
checking how to run the C preprocessor... /usr/bin/gcc-4.2 -std=gnu99 -E
checking for X... libraries , headers 
checking if GCC supports -fno-exceptions... yes
checking if GCC supports -fno-strict-aliasing... yes
checking if ld supports -no-undefined... no
checking if ld supports -Bsymbolic-functions... no
checking if toolchain supports sections... no

Configuration Summary
-------------------------------------------------------------------------
    Directories: prefix=/opt/local
                 bindir=${exec_prefix}/bin
                 datadir=${datarootdir}
                 datarootdir=${prefix}/share
                 exec_prefix=${prefix}
                 includedir=${prefix}/include
                 libdir=${exec_prefix}/lib
                 mandir=${datarootdir}/man
    Build fluid: YES
    Build tests: YES
Cross-compiling: NO
       Graphics: Quartz
Image Libraries: JPEG=System
                 PNG=System
                 ZLIB=System
Forms library:   YES
    Large Files: YES
         OpenGL: YES
        Threads: YES
   Allow std:: : NO
configure: creating ./config.status
config.status: creating makeinclude
config.status: creating fltk.list
config.status: creating fltk-config
config.status: creating fltk.spec
config.status: creating FL/Makefile
config.status: creating config.h
config.status: creating FL/fl_config.h
config.status: FL/fl_config.h is unchanged

-------------------------------------------------------------------------
  IMPORTANT NOTE:
-------------------------------------------------------------------------

  FLTK 1.4.x will be the last version(s) of FLTK supporting
  autotools (configure + provided Makefiles) to build FLTK.
  FLTK 1.5.0 and higher will only support FLTK builds using CMake.

  We suggest to explore and use the CMake build system generators
  for your own FLTK builds as soon as possible. Some new FLTK build
  options will only be supported by CMake based builds.
  Please see README.CMake.txt for details and instructions.

  User projects that use CMake for their own build can benefit
  substantially if the FLTK library has been built using CMake.

-------------------------------------------------------------------------

--->  Patching fltk-config: s|-arch [a-z0-9_]+||g
--->  Building fltk
Executing:  cd "/opt/local/var/macports/build/fltk-08af0cac/work/fltk-1.4.5" && /usr/bin/make -j2 -w all 
make: Entering directory `/opt/local/var/macports/build/fltk-08af0cac/work/fltk-1.4.5'
for dir in   src  fluid fltk-options test documentation; do\
		echo "=== making $dir ===";\
		(cd $dir; /usr/bin/make -w --jobserver-fds=6,7 -j) || exit 1;\
	done
=== making src ===
make[1]: Entering directory `/opt/local/var/macports/build/fltk-08af0cac/work/fltk-1.4.5/src'
echo Compiling Fl_cocoa.mm...
echo Compiling drivers/Cocoa/Fl_Cocoa_Printer_Driver.mm...
Compiling Fl_cocoa.mm...
/usr/bin/g++-4.2 -I.. -arch ppc -Os -Wno-deprecated-declarations -Wall -Wunused -Wno-format-y2k  -fPIC -fno-exceptions -fno-strict-aliasing -D_LARGEFILE_SOURCE -D_LARGEFILE64_SOURCE -D_THREAD_SAFE -D_REENTRANT  -pipe -Os -DFL_LIBRARY  -x objective-c++ -c Fl_cocoa.mm -o Fl_cocoa.o
Compiling drivers/Cocoa/Fl_Cocoa_Printer_Driver.mm...
/usr/bin/g++-4.2 -I.. -arch ppc -Os -Wno-deprecated-declarations -Wall -Wunused -Wno-format-y2k  -fPIC -fno-exceptions -fno-strict-aliasing -D_LARGEFILE_SOURCE -D_LARGEFILE64_SOURCE -D_THREAD_SAFE -D_REENTRANT  -pipe -Os -DFL_LIBRARY  -x objective-c++ -c drivers/Cocoa/Fl_Cocoa_Printer_Driver.mm -o drivers/Cocoa/Fl_Cocoa_Printer_Driver.o
Fl_cocoa.mm:106: warning: ignoring #pragma clang diagnostic
Fl_cocoa.mm:107: warning: ignoring #pragma clang diagnostic
Fl_cocoa.mm:108: warning: ignoring #pragma clang diagnostic
Fl_cocoa.mm:123: warning: ignoring #pragma clang diagnostic
Fl_cocoa.mm:862: warning: ignoring #pragma clang diagnostic
Fl_cocoa.mm:863: warning: ignoring #pragma clang diagnostic
Fl_cocoa.mm:867: warning: ignoring #pragma clang diagnostic
Fl_cocoa.mm:3779: warning: ignoring #pragma clang diagnostic
Fl_cocoa.mm:3780: warning: ignoring #pragma clang diagnostic
Fl_cocoa.mm:3782: warning: ignoring #pragma clang diagnostic
Fl_cocoa.mm:4442: warning: ignoring #pragma clang diagnostic
Fl_cocoa.mm:4443: warning: ignoring #pragma clang diagnostic
Fl_cocoa.mm:4451: warning: ignoring #pragma clang diagnostic
Fl_cocoa.mm:4633: warning: ignoring #pragma clang diagnostic
Fl_cocoa.mm:4634: warning: ignoring #pragma clang diagnostic
Fl_cocoa.mm:4636: warning: ignoring #pragma clang diagnostic
Fl_cocoa.mm: In function ‘BOOL -[FLView performKeyEquivalent:](FLView*, objc_selector*, NSEvent*)’:
Fl_cocoa.mm:2522: error: ‘NSEventModifierFlagFunction’ was not declared in this scope
echo Compiling Fl_Native_File_Chooser_MAC.mm...
Compiling Fl_Native_File_Chooser_MAC.mm...
/usr/bin/g++-4.2 -I.. -arch ppc -Os -Wno-deprecated-declarations -Wall -Wunused -Wno-format-y2k  -fPIC -fno-exceptions -fno-strict-aliasing -D_LARGEFILE_SOURCE -D_LARGEFILE64_SOURCE -D_THREAD_SAFE -D_REENTRANT  -pipe -Os -DFL_LIBRARY  -x objective-c++ -c Fl_Native_File_Chooser_MAC.mm -o Fl_Native_File_Chooser_MAC.o
make[1]: *** [Fl_cocoa.o] Error 1
make[1]: *** Waiting for unfinished jobs....
Fl_Native_File_Chooser_MAC.mm:713: warning: ignoring #pragma clang diagnostic
Fl_Native_File_Chooser_MAC.mm:714: warning: ignoring #pragma clang diagnostic
Fl_Native_File_Chooser_MAC.mm:716: warning: ignoring #pragma clang diagnostic
make[1]: Leaving directory `/opt/local/var/macports/build/fltk-08af0cac/work/fltk-1.4.5/src'
make: *** [all] Error 1
```

**Comment by barracuda156** [comment]
This commit causes the regression: https://github.com/fltk/fltk/commit/d4d1af2f7332c31dd4f86a55a1629c92c07f9a87

___________________________________________________________

@ManoloFLTK Hi, any chance of not breaking FLTK for us, please? 

https://github.com/fltk/fltk/commit/a35f76a256187d6feec11bc020899dcc7c7fb947
https://github.com/fltk/fltk/commit/3f56b8091d8e48c9d5bf82c9459dac61c49df9c6
https://github.com/fltk/fltk/commit/95e5b1b9c5ffea34c01becd518b11542d597daf8

That will be pretty painful to carry locally and keep rebasing :( 

Update. As pointed out below, this should be a separate issue, 1.4.5 fails not because of these specific commits.

**Comment by Albrecht-S** [comment]
@barracuda156 The commits you mention above are NOT in `branch-1.4`, i.e. not in the official release 1.4.5. They are, however, in the `master` branch which will be released as FLTK 1.5.0 in the future, and this will - IIRC - require at least macOS 10.7.

What is `/opt/local/var/macports/build/fltk-08af0cac/work/fltk-1.4.5` ? This **_looks like_** a checkout of `MacPorts` which I don't know personally. It doesn't look like an original FLTK build. And what does `08af0cac` mean? It **looks like** a commit hash, but such a commit does not exist in the FLTK repository.

**_Just a guess:_** did the `MacPorts` guys backport some commits from `master` to "their version" of FLTK 1.4.5 ?

I'm sure, BTW, that I tested release 1.4.5 on current macOS 26 (Tahoe) - which obviously doesn't mean that it would build on macOS 10.6. I don't have a 10.6 system available. Maybe @ManoloFLTK can tell the details.

Whatever it is, if you didn't build from an official FLTK release (tarball) or from a GitHub checkout, then we can't help.

-----

I apologize if my **guess** is wrong, please clarify what you are trying to build, i.e. where your sources come from. You should have done that in the first place -- please use the bug report template and fill in the details we request if you file another issue. TIA.

**Comment by barracuda156** [comment]
@Albrecht-S If I was using some patched version, I would mention that. The error comes exactly from the line which is mentioned in the log: https://github.com/fltk/fltk/blob/a9b1113516ffd15fc7602a6d425a317df30f4720/src/Fl_cocoa.mm#L2522 (this is 1.4.5).

MacPorts does not apply any patches (and neither did I): https://github.com/macports/macports-ports/blob/bed9a52499d05101740f104e1dc1976846693253/aqua/fltk/Portfile

To reproduce locally, replace 1.4.4 with 1.4.5 and update checksums here: https://github.com/macports/macports-ports/blob/bed9a52499d05101740f104e1dc1976846693253/aqua/fltk/Portfile#L34-L41
There was nothing to describe, since the procedure is trivial and the source is from official release.

P. S. What hashes are added to the build path is irrelevant to the matter. That is done to differentiate between potentially multiple build dirs for the same version of a given port (which will happen if I build from official source, that fails, and I build from overlay with some fixes added).

**Comment by barracuda156** [comment]
@ManoloFLTK Thank you for the fix! I will try the build soon.

**Comment by ManoloFLTK** [comment]
@barracuda156 The missing symbol that prevented building FLTK 1.4.5 for macOS using SDK 10.6 should be fixed with commit 88eedd3. Is it possible for MacPorts to use that commit rather than the official tarball as source of its FLTK port?

@Albrecht-S The initial description of this issue that 1.4.5 can't be built using macOS SDK 10.6 is correct. However, this issue initially mentionned that commits such as a35f76a were responsible for the building error. That's not correct as you found out and that's been changed in later edits to the issue description.

@barracuda156 The FLTK team has decided that, starting with the next planned release of FLTK 1.5, building would require support of C++-11. This in turn requires to remove support of all macOS versions earlier than 10.7. This decision won't be changed. FLTK 1.4.5 (+ a one-line patch) will therefore be the last version of FLTK usable on macOS for the PowerPC architecture.

**Comment by barracuda156** [comment]
@ManoloFLTK Requirement for C++11 does not logically entail requirement for 10.7+. Yes, I remember about a gcc bug with ObjC++, but that one is not FLTK problem and will be fixed with gcc upstream.

We can require C++11 or later, and still support 10.6 (in fact, even 10.4, though I do not care about that).

**Comment by barracuda156** [comment]
> Is it possible for MacPorts to use that commit rather than the official tarball as source of its FLTK port?

Adding a patch from your commit should work perfectly fine for MacPorts (or any package manager) case.

**Comment by barracuda156** [comment]
@ManoloFLTK Your fix worked, thank you. I close this issue as resolved. Question about 1.5.x is moved to https://github.com/fltk/fltk/issues/1425 (since it is a separate issue altogether).
