### ISSUE TITLE
Fluid: Compilation on older gcc fails

### ISSUE THREAD

**Issue by wcout** [fltk/fltk#605]
Happen to compile FLTK with a very old gcc (4.8.2) on Ubuntu 14.04

There is one error from success with a recent change in Fluid:

`````
Compiling fluid.cxx...
fluid.cxx: In constructor ‘Project::Project()’:
fluid.cxx:265:24: error: incompatible types in assignment of ‘const char [1]’ to ‘char [2049]’
   code_file_name(".cxx")
                        ^
`````

But this error message is misleading, the real issue is with this line:
https://github.com/fltk/fltk/blob/993b7da3b513ecb33730ab76828e64dcb6b80115/fluid/fluid.cxx#L257

**Comment by erco77** [comment]
> i18n_program[0] = 0;

Yikes! Yeah, I'd think that shouldn't even be allowed..

**Comment by wcout** [comment]
Sorry, but actually I tagged the wrong line, its 257 (just corrected above).

**Comment by MatthiasWM** [comment]
Thanks for the report. I am in the process of moving all cha pointers and char arrays to Fl_String. No clue why this throws an error though.

**Comment by erco77** [comment]
Oh, OK -- and regarding my comment of course arr[0] = 0; works, but I _thought_ I was seeing `char i18n_program[0] = 0;`, which rebooted my brain. Surprisingly you can compile `char arr[0];` without error (unless you have -pedantic turned on):
```
$ cat f.cxx
int main() {
    char a[0];   // yikes
    a[0] = a[0];  // use it to avoid warnings about unused vars
    return 0;
}

$ g++ f.cxx -o f       <-- compiles ok?!
$ ./f                  <-- even runs without crashing, lol
$

**Comment by MatthiasWM** [comment]
Attempt to fix this here: #606. Could you check if it actually works on your old compiler?

**Comment by wcout** [comment]
Yeah, this changes compile with gcc 4.8.2

But there is another on left (didn't get it last time - was on another VB):

`````
=== making src ===
Compiling Fl_JPEG_Image.cxx...
Fl_JPEG_Image.cxx: In member function ‘void Fl_JPEG_Image::load_jpg_(const char*, const char*, const unsigned char*, int)’:
Fl_JPEG_Image.cxx:307:53: error: invalid conversion from ‘const unsigned char*’ to ‘unsigned char*’ [-fpermissive]
       jpeg_mem_src(&dinfo, data, (size_t)data_length);
                                                     ^
In file included from Fl_JPEG_Image.cxx:50:0:
/usr/include/jpeglib.h:1008:14: error:   initializing argument 2 of ‘void jpeg_mem_src(j_decompress_ptr, unsigned char*, long unsigned int)’ [-fpermissive]
 EXTERN(void) jpeg_mem_src JPP((j_decompress_ptr cinfo,
`````
Casting away the constness of  `data`  works.

**Comment by MatthiasWM** [comment]
id I catch that with my last commit to master? Can this be closed?

**Comment by wcout** [comment]
Yes, FLTK compiles now flawlessly with gcc 4.8.2.
