### ISSUE TITLE
build failure related to FL_OVERRIDE

### ISSUE THREAD

**Issue by pdhahn** [fltk/fltk#619]
I updated my FLTK 1.4 to the latest commit (2c5a5ce948a47d067659f4745039af44ede5829b) and now I get the following build error on my old CentOS 6 system:

```
.../fltk/fltk-clone/src/Fl_x.cxx: In static member function \u2018static void Fl_X::make_xid(Fl_Window*, XVisualInfo*, Colormap)\u2019:
.../fltk/fltk-clone/src/Fl_x.cxx:2415:23: error: expected unqualified-id before \u2018(\u2019 token
   if (win->FL_OVERRIDE()) {
                       ^
[ 37%] Building CXX object src/CMakeFiles/fltk.dir/drivers/Xlib/Fl_Xlib_Graphics_Driver_font_xft.cxx.o
.../fltk/fltk-clone/src/Fl_x.cxx: In member function \u2018void Fl_X11_Window_Driver::sendxjunk()\u2019:
.../fltk/fltk-clone/src/Fl_x.cxx:2616:36: error: expected unqualified-id before \u2018(\u2019 token
   if (w->parent() || w->FL_OVERRIDE()) return; // it's not a window manager window!
                                    ^
make[2]: *** [src/CMakeFiles/fltk.dir/Fl_x.cxx.o] Error 1

```
I presume the problem with FL_OVERRIDE was introduced in commit 44c874b731f9f58c2f50c3c6076371058cbe26e3 but I haven't verified.

**Comment by MatthiasWM** [comment]
Thanks for the report. I have no idea how that could have slipped. We have compiled the code on so many platforms... .

Anyway, it's fixed in the master branch.

**Comment by MatthiasWM** [comment]
Please confirm if it is fixed for you too. Thanks.

**Comment by Albrecht-S** [comment]
> I have no idea how that could have slipped. We have compiled the code on so many platforms...

Obviously we missed testing on C++ standard less than C++11 where FL_OVERRIDE is `""` (empty). You always try to verify the new code, sometimes neglecting old code/environments. Such things happen but fortunately the wide user base finds and reports such issues (quickly).

Thanks @pdhahn.

**Comment by pdhahn** [comment]
Yes I can confirm it is fixed now. Thanks!
