### PR TITLE
Fl_cocoa.mm: fix Apple macro for PPC case

### PR DESCRIPTION
**Pull request by barracuda156**
This fixes the build on 10.6 when building for `ppc`. Has no effect on other platforms.

### CODE REVIEW

**Comment by ManoloFLTK** [comment]
Thanks for this input.
However, I routinely build FLTK for 4 architectures (ppc, i386, x86_64 and arm64) and see no compilation error for ppc and SDK 10.6. Why do you think a change to source code is necessary?

**Comment by barracuda156** [comment]
@ManoloFLTK Thank you for responding. 10.6 PPC (native one) SDK is somewhat closer to 10.5 SDK, and some features of 10.6.8 SDK (what you have in Xcode 3.2.6) are not supported. In fact even 10.6.8 Rosetta will not be 100% identical in terms of features when building for x86 and ppc (there is no ppc64 in it, it is impossible to build any ppc64 code against any version of 10.6 SDK, including available developer versions).

**Comment by ManoloFLTK** [comment]
I have checked that `NSPasteboardTypeString, NSPasteboardTypePDF`, and `NSPasteboardTypeTIFF` are all defined in
`…/MacOSX10.6.sdk/System/Library/Frameworks/AppKit.framework/Versions/C/Headers/NSPasteboard.h`. So compilation should not fail.

Without the proposed patch, do you get an error at compile time, link time, run time?

**Comment by barracuda156** [comment]
@ManoloFLTK Here is how the build fails:
```
--->  Building fltk
Executing:  cd "/opt/local/var/macports/build/_opt_PPCSnowLeopardPorts_aqua_fltk/fltk/work/fltk-1.3.8" && /usr/bin/make -j6 -w all 
make: Entering directory `/opt/local/var/macports/build/_opt_PPCSnowLeopardPorts_aqua_fltk/fltk/work/fltk-1.3.8'
for dir in  src  fluid test documentation; do\
		echo "=== making $dir ===";\
		(cd $dir; /usr/bin/make -w --jobserver-fds=5,6 -j) || exit 1;\
	done
=== making src ===
make[1]: Entering directory `/opt/local/var/macports/build/_opt_PPCSnowLeopardPorts_aqua_fltk/fltk/work/fltk-1.3.8/src'
echo Compiling Fl_cocoa.mm...
echo Compiling Fl_Quartz_Printer.mm...
echo Compiling Fl_Native_File_Chooser_MAC.mm...
echo Compiling Fl_Sys_Menu_Bar.mm...
Compiling Fl_cocoa.mm...
Compiling Fl_Quartz_Printer.mm...
Compiling Fl_Native_File_Chooser_MAC.mm...
Compiling Fl_Sys_Menu_Bar.mm...
/usr/bin/g++-4.2 -I.. -arch ppc -Os -Wno-deprecated-declarations -Wall -Wunused -Wno-format-y2k  -fPIC -fno-exceptions -fno-strict-aliasing -D_LARGEFILE_SOURCE -D_LARGEFILE64_SOURCE -D_THREAD_SAFE -D_REENTRANT  -pipe -Os -DFL_LIBRARY -x objective-c++ -c Fl_Sys_Menu_Bar.mm -o Fl_Sys_Menu_Bar.o
/usr/bin/g++-4.2 -I.. -arch ppc -Os -Wno-deprecated-declarations -Wall -Wunused -Wno-format-y2k  -fPIC -fno-exceptions -fno-strict-aliasing -D_LARGEFILE_SOURCE -D_LARGEFILE64_SOURCE -D_THREAD_SAFE -D_REENTRANT  -pipe -Os -DFL_LIBRARY -x objective-c++ -c Fl_Native_File_Chooser_MAC.mm -o Fl_Native_File_Chooser_MAC.o
/usr/bin/g++-4.2 -I.. -arch ppc -Os -Wno-deprecated-declarations -Wall -Wunused -Wno-format-y2k  -fPIC -fno-exceptions -fno-strict-aliasing -D_LARGEFILE_SOURCE -D_LARGEFILE64_SOURCE -D_THREAD_SAFE -D_REENTRANT  -pipe -Os -DFL_LIBRARY -x objective-c++ -c Fl_Quartz_Printer.mm -o Fl_Quartz_Printer.o
/usr/bin/g++-4.2 -I.. -arch ppc -Os -Wno-deprecated-declarations -Wall -Wunused -Wno-format-y2k  -fPIC -fno-exceptions -fno-strict-aliasing -D_LARGEFILE_SOURCE -D_LARGEFILE64_SOURCE -D_THREAD_SAFE -D_REENTRANT  -pipe -Os -DFL_LIBRARY -x objective-c++ -c Fl_cocoa.mm -o Fl_cocoa.o
echo Compiling Fl.cxx...
echo Compiling Fl_Adjuster.cxx...
Compiling Fl.cxx...
/usr/bin/g++-4.2 -I.. -arch ppc    -Os -Wno-deprecated-declarations -Wall -Wunused -Wno-format-y2k  -fPIC -fno-exceptions -fno-strict-aliasing -D_LARGEFILE_SOURCE -D_LARGEFILE64_SOURCE -D_THREAD_SAFE -D_REENTRANT  -pipe -Os -DFL_LIBRARY -c Fl.cxx -o Fl.o
Compiling Fl_Adjuster.cxx...
/usr/bin/g++-4.2 -I.. -arch ppc    -Os -Wno-deprecated-declarations -Wall -Wunused -Wno-format-y2k  -fPIC -fno-exceptions -fno-strict-aliasing -D_LARGEFILE_SOURCE -D_LARGEFILE64_SOURCE -D_THREAD_SAFE -D_REENTRANT  -pipe -Os -DFL_LIBRARY -c Fl_Adjuster.cxx -o Fl_Adjuster.o
echo Compiling Fl_Bitmap.cxx...
Compiling Fl_Bitmap.cxx...
/usr/bin/g++-4.2 -I.. -arch ppc    -Os -Wno-deprecated-declarations -Wall -Wunused -Wno-format-y2k  -fPIC -fno-exceptions -fno-strict-aliasing -D_LARGEFILE_SOURCE -D_LARGEFILE64_SOURCE -D_THREAD_SAFE -D_REENTRANT  -pipe -Os -DFL_LIBRARY -c Fl_Bitmap.cxx -o Fl_Bitmap.o
echo Compiling Fl_Browser.cxx...
Compiling Fl_Browser.cxx...
/usr/bin/g++-4.2 -I.. -arch ppc    -Os -Wno-deprecated-declarations -Wall -Wunused -Wno-format-y2k  -fPIC -fno-exceptions -fno-strict-aliasing -D_LARGEFILE_SOURCE -D_LARGEFILE64_SOURCE -D_THREAD_SAFE -D_REENTRANT  -pipe -Os -DFL_LIBRARY -c Fl_Browser.cxx -o Fl_Browser.o
Fl_cocoa.mm:112: error: ‘NSPasteboardTypeTIFF’ was not declared in this scope
Fl_cocoa.mm:113: error: ‘NSPasteboardTypePDF’ was not declared in this scope
Fl_cocoa.mm:115: error: ‘NSPasteboardTypeString’ was not declared in this scope
Fl_cocoa.mm: In member function ‘void Fl_Window::fullscreen_x()’:
Fl_cocoa.mm:3090: warning: ‘FLWindow’ may not respond to ‘-setStyleMask:’
Fl_cocoa.mm:3090: warning: (Messages without a matching method signature
Fl_cocoa.mm:3090: warning: will be assumed to return ‘id’ and accept
Fl_cocoa.mm:3090: warning: ‘...’ as arguments.)
Fl_cocoa.mm: In member function ‘void Fl_Window::fullscreen_off_x(int, int, int, int)’:
Fl_cocoa.mm:3129: warning: ‘FLWindow’ may not respond to ‘-setStyleMask:’
echo Compiling Fl_Browser_.cxx...
Compiling Fl_Browser_.cxx...
/usr/bin/g++-4.2 -I.. -arch ppc    -Os -Wno-deprecated-declarations -Wall -Wunused -Wno-format-y2k  -fPIC -fno-exceptions -fno-strict-aliasing -D_LARGEFILE_SOURCE -D_LARGEFILE64_SOURCE -D_THREAD_SAFE -D_REENTRANT  -pipe -Os -DFL_LIBRARY -c Fl_Browser_.cxx -o Fl_Browser_.o
echo Compiling Fl_Browser_load.cxx...
Compiling Fl_Browser_load.cxx...
/usr/bin/g++-4.2 -I.. -arch ppc    -Os -Wno-deprecated-declarations -Wall -Wunused -Wno-format-y2k  -fPIC -fno-exceptions -fno-strict-aliasing -D_LARGEFILE_SOURCE -D_LARGEFILE64_SOURCE -D_THREAD_SAFE -D_REENTRANT  -pipe -Os -DFL_LIBRARY -c Fl_Browser_load.cxx -o Fl_Browser_load.o
make[1]: *** [Fl_cocoa.o] Error 1
make[1]: *** Waiting for unfinished jobs....
```

This is on native 10.6 PPC:
```
36-25% sw_vers
ProductName:	Mac OS X
ProductVersion:	10.6
BuildVersion:	10A190
36-25% uname -a
Darwin 36-25.wireless-city.scu.edu.tw 10.0.0d2 Darwin Kernel Version 10.0.0d2: Fri Oct 10 19:37:52 PDT 2008; root:xnu-1346.7~1/RELEASE_PPC Power Macintosh
```

**Comment by ManoloFLTK** [comment]
OK. So not all 10.6 SDKs are created equal! That's a pity.

I'm being peeky because I want FLTK to support building and running for all macOS versions since 10.3. I believe a potential issue emerges with the proposed change:
```
#if (MAC_OS_X_VERSION_MAX_ALLOWED < MAC_OS_X_VERSION_10_6) || defined(__POWERPC__)
```
What would happen using SDK 10.7 on PPC? Could there be a conflict between the `#define` done inside FLTK and file `NSPasteboard.h` of the SDK? 

What about this more careful variant :

```
#if defined(__POWERPC__)
#  define BORDER_VERSION MAC_OS_X_VERSION_10_7
#else
#  define BORDER_VERSION MAC_OS_X_VERSION_10_6
#endif
#if MAC_OS_X_VERSION_MAX_ALLOWED < BORDER_VERSION
```

**Comment by barracuda156** [comment]
@ManoloFLTK It is impossible to use any SDK above 10.6.8 for building for `ppc`, since there are no `ppc` slices anymore. Even though one may build for `ppc` on a later MacOS using cross-compiler, earlier SDK must be used, which actually supports `ppc` arch (i.e., you will need to point to a specific SDK with sysroot and pass flags for macOS version compatibility). Then, if you build against 10.6.8 SDK (which is possible), resulting binary won’t work correctly on any native PowerPC system (with regard to discussed function), since there is no such a system which matches to 10.6.8 SDK.

**Comment by ManoloFLTK** [comment]
Yes, sorry, I saw after that my pojnt makes no sense because PPC support stopped at 10.6. I'm going to commit this PR. Many thanks.

**Comment by barracuda156** [comment]
@ManoloFLTK Thank you!

**Comment by ManoloFLTK** [comment]
I've added an extra comment line to explain why PPC-specific code is necessary, because it's easy to forget.
