### ISSUE TITLE
Build using a GLU from a non-standard location

### ISSUE THREAD

**Issue by jwillikers** [fltk/fltk#952]
**Describe the bug**

I'm trying to update the [fltk Conan package](https://github.com/conan-io/conan-center-index/blob/master/recipes/fltk/all/conanfile.py) to use a `mesa-glu` package in [this PR](https://github.com/conan-io/conan-center-index/pull/22958).
This is problematic since GLU's library and headers are assumed to be in the same locations as the `GL` library and headers.
This is specific to the CMake build system.

**To Reproduce**

Must reproduce in an environment without the system GLU installed.

1. `pip3 install conan`
1. `conan profile detect`
2. `git clone https://github.com/jwillikers/conan-center-index.git`
3. `cd conan-center-index/recipes/fltk/all/`
4. `git switch fltk-1.4.0`
5. `conan create . --build missing --version 1.4.0`
6. Wait for everything to build and you should see the error.

**Expected behavior**

CMake should locate the `GL/glu.h` header file and `GLU` library independent of the `GL/gl.h` header file and `GL` library and include them in the build appropriately.

**Screenshots**

```
fltk/1.4.0: Running CMake.configure()
fltk/1.4.0: RUN: cmake -G "Ninja" -DCMAKE_TOOLCHAIN_FILE="/home/jordan/.conan2/p/b/fltk6c8d47e27bb45/b/build/Debug/generators/conan_toolchain.cmake" -DCMAKE_INSTALL_PREFIX="/home/jordan/.conan2/p/b/fltk6c8d47e27bb45/p" -DCMAKE_POLICY_DEFAULT_CMP0091="NEW" -DCMAKE_BUILD_TYPE="Debug" "/home/jordan/.conan2/p/b/fltk6c8d47e27bb45/b/src"
-- Using Conan toolchain: /home/jordan/.conan2/p/b/fltk6c8d47e27bb45/b/build/Debug/generators/conan_toolchain.cmake
-- Conan toolchain: Setting CMAKE_POSITION_INDEPENDENT_CODE=ON (options.fPIC)
-- Conan toolchain: C++ Standard 20 with extensions OFF
-- Conan toolchain: Setting BUILD_SHARED_LIBS = OFF
-- The C compiler identification is GNU 13.2.1
-- The CXX compiler identification is GNU 13.2.1
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working C compiler: /usr/bin/gcc - skipped
-- Detecting C compile features
-- Detecting C compile features - done
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Check for working CXX compiler: /usr/bin/g++ - skipped
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Looking for sys/types.h
-- Looking for sys/types.h - found
-- Looking for stdint.h
-- Looking for stdint.h - found
-- Looking for stddef.h
-- Looking for stddef.h - found
-- Check size of short
-- Check size of short - done
-- Check size of int
-- Check size of int - done
-- Check size of long
-- Check size of long - done
-- Check size of long long
-- Check size of long long - done
-- Found PkgConfig: /usr/bin/pkg-config (found version "1.9.5") 
-- Looking for POSIX compatible scandir
-- POSIX compatible scandir - found
-- Could NOT find Doxygen (missing: DOXYGEN_EXECUTABLE) 
-- Conan: Target declared 'ZLIB::ZLIB'
-- Conan: Target declared 'PNG::PNG'
-- Looking for png.h
-- Looking for png.h - found
-- Conan: Target declared 'JPEG::JPEG'
-- Checking for module 'wayland-client>=1.18'
--   Package 'wayland-client', required by 'virtual:world', not found
-- Checking for module 'wayland-cursor'
--   Package 'wayland-cursor', required by 'virtual:world', not found
-- Checking for module 'wayland-protocols>=1.15'
--   Found wayland-protocols, version 1.33
-- Checking for module 'xkbcommon'
--   Package 'xkbcommon', required by 'virtual:world', not found
-- Not all software modules 'wayland-client>=1.18 wayland-cursor wayland-protocols>=1.15 xkbcommon' are present
-- Consequently, FLTK_BACKEND_WAYLAND is turned off.
-- Conan: Target declared 'Freetype::Freetype'
-- Conan: Including build module from '/home/jordan/.conan2/p/freetfcb681ee3b844/p/lib/cmake/conan-official-freetype-variables.cmake'
-- Found X11: /home/jordan/.conan2/p/xorg-d070c63754573/p/include   
-- Looking for XOpenDisplay in /usr/lib64/libX11.so;/usr/lib64/libXext.so
-- Looking for XOpenDisplay in /usr/lib64/libX11.so;/usr/lib64/libXext.so - found
-- Looking for gethostbyname
-- Looking for gethostbyname - found
-- Looking for connect
-- Looking for connect - found
-- Looking for remove
-- Looking for remove - found
-- Looking for shmat
-- Looking for shmat - found
-- Looking for IceConnectionNumber in ICE
-- Looking for IceConnectionNumber in ICE - found
-- Looking for glXGetProcAddressARB
-- Looking for glXGetProcAddressARB - not found
-- Performing Test CMAKE_HAVE_LIBC_PTHREAD
-- Performing Test CMAKE_HAVE_LIBC_PTHREAD - Success
-- Found Threads: TRUE  

-- Configuration Summary for FLTK 1.4.0 generated by CMake 3.27.7 --

-- The following OPTIONAL packages have been found:

 * ZLIB
 * PNG
 * JPEG

-- The following OPTIONAL packages have not been found:

 * Doxygen

-- Static libraries    will be built in: /var/home/jordan/.conan2/p/b/fltk6c8d47e27bb45/b/build/Debug/lib
-- Shared libraries    will not be built (set FLTK_BUILD_SHARED_LIBS=ON to build)
-- The forms library   will be built in: /var/home/jordan/.conan2/p/b/fltk6c8d47e27bb45/b/build/Debug/lib
-- The OpenGL library  will be built in: /var/home/jordan/.conan2/p/b/fltk6c8d47e27bb45/b/build/Debug/lib
-- fluid               will be built in: /var/home/jordan/.conan2/p/b/fltk6c8d47e27bb45/b/build/Debug/bin
-- fltk-options        will be built in: /var/home/jordan/.conan2/p/b/fltk6c8d47e27bb45/b/build/Debug/bin
-- Test programs       will not be built (set FLTK_BUILD_TEST=ON to build)
-- Example programs    will not be built (set FLTK_BUILD_EXAMPLES=ON to build)
-- 
-- Build configuration      Debug

-- Image Libraries          JPEG = System: /home/jordan/.conan2/p/libjp29f5b39e2aeaa/p/lib/libjpeg.a
--                          PNG  = System: /home/jordan/.conan2/p/libpn8e98f56ea81b4/p/lib/libpng.a
--                          ZLIB = System: /home/jordan/.conan2/p/zlibb3b3150917a76/p/lib/libz.a

-- Use Wayland              No (X11 is used)
-- All drawing uses Cairo   No
-- Use Pango                No
-- Use Xft                  Yes
-- Fl_Cairo_Window support  No
-- Use std::                No

-- End of Configuration Summary --

-- Configuring done (3.1s)
-- Generating done (0.0s)
-- Build files have been written to: /var/home/jordan/.conan2/p/b/fltk6c8d47e27bb45/b/build/Debug

fltk/1.4.0: Running CMake.build()
fltk/1.4.0: RUN: cmake --build "/home/jordan/.conan2/p/b/fltk6c8d47e27bb45/b/build/Debug" -- -j20
[212/269] Building CXX object src/CMakeFiles/fltk_gl.dir/gl_draw.cxx.o
FAILED: src/CMakeFiles/fltk_gl.dir/gl_draw.cxx.o 
/usr/bin/g++ -DFL_LIBRARY -D_FILE_OFFSET_BITS=64 -D_LARGEFILE64_SOURCE -D_LARGEFILE_SOURCE -I/home/jordan/.conan2/p/libpn8e98f56ea81b4/p/include -I/var/home/jordan/.conan2/p/b/fltk6c8d47e27bb45/b/build/Debug/src/.. -I/home/jordan/.conan2/p/b/fltk6c8d47e27bb45/b/src/src/.. -m64 -g -std=c++20 -fPIC -MD -MT src/CMakeFiles/fltk_gl.dir/gl_draw.cxx.o -MF src/CMakeFiles/fltk_gl.dir/gl_draw.cxx.o.d -o src/CMakeFiles/fltk_gl.dir/gl_draw.cxx.o -c /home/jordan/.conan2/p/b/fltk6c8d47e27bb45/b/src/src/gl_draw.cxx
In file included from /home/jordan/.conan2/p/b/fltk6c8d47e27bb45/b/src/src/gl_draw.cxx:44:
/home/jordan/.conan2/p/b/fltk6c8d47e27bb45/b/src/src/../FL/glu.h:42:14: fatal error: GL/glu.h: No such file or directory
   42 | #    include <GL/glu.h>
      |              ^~~~~~~~~~
compilation terminated.
[231/269] Building CXX object src/CMakeFiles/fltk_images.dir/nanosvg.cxx.o
ninja: build stopped: subcommand failed.

fltk/1.4.0: ERROR: 
Package '20b246d44c89779315daae4f71325e8808463962' build failed
```

**FLTK Version**
Please complete the following information and delete non-applicable lines:
 - Version: 1.3.8 through the current master
 - Downloaded and self-built from: Conan
 - If from Git, branch: master
 - If from Git, commit: 05a95e146b2429154b360030d098f0dae5555706

**FLTK Configure / Build Options**

```
cmake -G "Ninja" \
    -DCMAKE_TOOLCHAIN_FILE="/home/jordan/.conan2/p/b/fltk6c8d47e27bb45/b/build/Debug/generators/conan_toolchain.cmake" \
    -DCMAKE_INSTALL_PREFIX="/home/jordan/.conan2/p/b/fltk6c8d47e27bb45/p" \
    -DCMAKE_POLICY_DEFAULT_CMP0091="NEW" \
    -DCMAKE_BUILD_TYPE="Debug" "/home/jordan/.conan2/p/b/fltk6c8d47e27bb45/b/src"
```

conan_toolchain.cmake

```
# Conan automatically generated toolchain file
# DO NOT EDIT MANUALLY, it will be overwritten

# Avoid including toolchain file several times (bad if appending to variables like
#   CMAKE_CXX_FLAGS. See https://github.com/android/ndk/issues/323
include_guard()

message(STATUS "Using Conan toolchain: ${CMAKE_CURRENT_LIST_FILE}")

if(${CMAKE_VERSION} VERSION_LESS "3.15")
    message(FATAL_ERROR "The 'CMakeToolchain' generator only works with CMake >= 3.15")
endif()




########## generic_system block #############
# Definition of system, platform and toolset
#############################################





set(CMAKE_C_COMPILER "gcc")
set(CMAKE_CXX_COMPILER "g++")
set(CMAKE_ASM_COMPILER "gcc")


message(STATUS "Conan toolchain: Setting CMAKE_POSITION_INDEPENDENT_CODE=ON (options.fPIC)")
set(CMAKE_POSITION_INDEPENDENT_CODE ON CACHE BOOL "Position independent code")


string(APPEND CONAN_CXX_FLAGS " -m64")
string(APPEND CONAN_C_FLAGS " -m64")
string(APPEND CONAN_SHARED_LINKER_FLAGS " -m64")
string(APPEND CONAN_EXE_LINKER_FLAGS " -m64")



message(STATUS "Conan toolchain: C++ Standard 20 with extensions OFF")
set(CMAKE_CXX_STANDARD 20)
set(CMAKE_CXX_EXTENSIONS OFF)
set(CMAKE_CXX_STANDARD_REQUIRED ON)

# Conan conf flags start: 
# Conan conf flags end

foreach(config IN LISTS CMAKE_CONFIGURATION_TYPES)
    string(TOUPPER ${config} config)
    if(DEFINED CONAN_CXX_FLAGS_${config})
      string(APPEND CMAKE_CXX_FLAGS_${config}_INIT " ${CONAN_CXX_FLAGS_${config}}")
    endif()
    if(DEFINED CONAN_C_FLAGS_${config})
      string(APPEND CMAKE_C_FLAGS_${config}_INIT " ${CONAN_C_FLAGS_${config}}")
    endif()
    if(DEFINED CONAN_SHARED_LINKER_FLAGS_${config})
      string(APPEND CMAKE_SHARED_LINKER_FLAGS_${config}_INIT " ${CONAN_SHARED_LINKER_FLAGS_${config}}")
    endif()
    if(DEFINED CONAN_EXE_LINKER_FLAGS_${config})
      string(APPEND CMAKE_EXE_LINKER_FLAGS_${config}_INIT " ${CONAN_EXE_LINKER_FLAGS_${config}}")
    endif()
endforeach()

if(DEFINED CONAN_CXX_FLAGS)
  string(APPEND CMAKE_CXX_FLAGS_INIT " ${CONAN_CXX_FLAGS}")
endif()
if(DEFINED CONAN_C_FLAGS)
  string(APPEND CMAKE_C_FLAGS_INIT " ${CONAN_C_FLAGS}")
endif()
if(DEFINED CONAN_SHARED_LINKER_FLAGS)
  string(APPEND CMAKE_SHARED_LINKER_FLAGS_INIT " ${CONAN_SHARED_LINKER_FLAGS}")
endif()
if(DEFINED CONAN_EXE_LINKER_FLAGS)
  string(APPEND CMAKE_EXE_LINKER_FLAGS_INIT " ${CONAN_EXE_LINKER_FLAGS}")
endif()


get_property( _CMAKE_IN_TRY_COMPILE GLOBAL PROPERTY IN_TRY_COMPILE )
if(_CMAKE_IN_TRY_COMPILE)
    message(STATUS "Running toolchain IN_TRY_COMPILE")
    return()
endif()

set(CMAKE_FIND_PACKAGE_PREFER_CONFIG ON)

# Definition of CMAKE_MODULE_PATH
# the generators folder (where conan generates files, like this toolchain)
list(PREPEND CMAKE_MODULE_PATH ${CMAKE_CURRENT_LIST_DIR})

# Definition of CMAKE_PREFIX_PATH, CMAKE_XXXXX_PATH
# The Conan local "generators" folder, where this toolchain is saved.
list(PREPEND CMAKE_PREFIX_PATH ${CMAKE_CURRENT_LIST_DIR} )
list(PREPEND CMAKE_LIBRARY_PATH "/home/jordan/.conan2/p/libjp29f5b39e2aeaa/p/lib" "/home/jordan/.conan2/p/b/mesa-460f153ef9bf6/p/lib" "/home/jordan/.conan2/p/libglc1db030d59b95/p/lib" "/home/jordan/.conan2/p/b/fontcca7d787242e00/p/lib" "/home/jordan/.conan2/p/freetfcb681ee3b844/p/lib" "/home/jordan/.conan2/p/libpn8e98f56ea81b4/p/lib" "/home/jordan/.conan2/p/zlibb3b3150917a76/p/lib" "/home/jordan/.conan2/p/bzip22348f04aff6b8/p/lib" "/home/jordan/.conan2/p/brotla6d859159cab4/p/lib" "/home/jordan/.conan2/p/expat6bbba55330317/p/lib" "/home/jordan/.conan2/p/util-9390e578fbb04/p/lib")
list(PREPEND CMAKE_INCLUDE_PATH "/home/jordan/.conan2/p/libjp29f5b39e2aeaa/p/include" "/home/jordan/.conan2/p/b/mesa-460f153ef9bf6/p/include" "/home/jordan/.conan2/p/libglc1db030d59b95/p/include" "/home/jordan/.conan2/p/xorg-d070c63754573/p/include" "/home/jordan/.conan2/p/xorg-d070c63754573/p/include/X11" "/home/jordan/.conan2/p/b/fontcca7d787242e00/p/include" "/home/jordan/.conan2/p/freetfcb681ee3b844/p/include" "/home/jordan/.conan2/p/freetfcb681ee3b844/p/include/freetype2" "/home/jordan/.conan2/p/libpn8e98f56ea81b4/p/include" "/home/jordan/.conan2/p/zlibb3b3150917a76/p/include" "/home/jordan/.conan2/p/bzip22348f04aff6b8/p/include" "/home/jordan/.conan2/p/brotla6d859159cab4/p/include" "/home/jordan/.conan2/p/brotla6d859159cab4/p/include/brotli" "/home/jordan/.conan2/p/expat6bbba55330317/p/include" "/home/jordan/.conan2/p/util-9390e578fbb04/p/include" "/home/jordan/.conan2/p/util-9390e578fbb04/p/include/uuid")



if (DEFINED ENV{PKG_CONFIG_PATH})
set(ENV{PKG_CONFIG_PATH} "${CMAKE_CURRENT_LIST_DIR}:$ENV{PKG_CONFIG_PATH}")
else()
set(ENV{PKG_CONFIG_PATH} "${CMAKE_CURRENT_LIST_DIR}:")
endif()




message(STATUS "Conan toolchain: Setting BUILD_SHARED_LIBS = OFF")
set(BUILD_SHARED_LIBS OFF CACHE BOOL "Build shared libraries")

set(CMAKE_INSTALL_PREFIX "/home/jordan/.conan2/p/b/fltk6c8d47e27bb45/p")
set(CMAKE_INSTALL_BINDIR "bin")
set(CMAKE_INSTALL_SBINDIR "bin")
set(CMAKE_INSTALL_LIBEXECDIR "bin")
set(CMAKE_INSTALL_LIBDIR "lib")
set(CMAKE_INSTALL_INCLUDEDIR "include")
set(CMAKE_INSTALL_OLDINCLUDEDIR "include")


# Variables
set(OPTION_BUILD_SHARED_LIBS "False" CACHE STRING "Variable OPTION_BUILD_SHARED_LIBS conan-toolchain defined")
set(FLTK_BUILD_TEST OFF CACHE BOOL "Variable FLTK_BUILD_TEST conan-toolchain defined")
set(FLTK_BUILD_EXAMPLES OFF CACHE BOOL "Variable FLTK_BUILD_EXAMPLES conan-toolchain defined")
set(OPTION_USE_GL "True" CACHE STRING "Variable OPTION_USE_GL conan-toolchain defined")
set(OPTION_USE_THREADS "True" CACHE STRING "Variable OPTION_USE_THREADS conan-toolchain defined")
set(OPTION_BUILD_HTML_DOCUMENTATION OFF CACHE BOOL "Variable OPTION_BUILD_HTML_DOCUMENTATION conan-toolchain defined")
set(OPTION_BUILD_PDF_DOCUMENTATION OFF CACHE BOOL "Variable OPTION_BUILD_PDF_DOCUMENTATION conan-toolchain defined")
set(OPTION_USE_XFT "False" CACHE STRING "Variable OPTION_USE_XFT conan-toolchain defined")
set(OPTION_ABI_VERSION "10400" CACHE STRING "Variable OPTION_ABI_VERSION conan-toolchain defined")
set(OPTION_USE_SYSTEM_LIBJPEG ON CACHE BOOL "Variable OPTION_USE_SYSTEM_LIBJPEG conan-toolchain defined")
set(OPTION_USE_SYSTEM_ZLIB ON CACHE BOOL "Variable OPTION_USE_SYSTEM_ZLIB conan-toolchain defined")
set(OPTION_USE_SYSTEM_LIBPNG ON CACHE BOOL "Variable OPTION_USE_SYSTEM_LIBPNG conan-toolchain defined")
# Variables  per configuration


# Preprocessor definitions
# Preprocessor definitions per configuration


if(CMAKE_POLICY_DEFAULT_CMP0091)  # Avoid unused and not-initialized warnings
endif()
```

```
cmake --build "/home/jordan/.conan2/p/b/fltk6c8d47e27bb45/b/build/Debug" -- -j20
```

**Operating System / Platform:**
 - OS: Linux
 - OS Version: Fedora 39

**Linux/Unix Runtime, if applicable:**
 - X11

**Additional context**

**Comment by jwillikers** [comment]
> @jwillikers Thanks for this report and your proposed fix in PR #953. I appreciate both very much because I don't have Conan installed. I'm now going to check #953...

Awesome and you're welcome! Let me know if you need anything.

**Comment by jwillikers** [comment]
> I tested the PR on my Linux system and I take it that this works for you with Conan - which I didn't test explicitly.
> 
> I'm now going to checkout and test your PR #954 which looks good, BTW.

Yes, I've tested with Conan for Linux.

**Comment by Albrecht-S** [comment]
Thanks for confirmation.
